### ISSUE TITLE
Thanks for showing this off! Api Key FYI

### ISSUE THREAD

**Issue by rahul-evenup-ai** [catid/self-discover#2]
Just a heads up if that was left there by accident, there's an api key in `self_discover.py`

**Comment by Flecart** [comment]
devnuc.lan is probably only accessible from his network, so not a big problem.

**Comment by catid** [comment]
I think the main reason I should not include the API key is so that people stop messaging me there's an API key in the code lol

**Comment by Flecart** [comment]
Lol
